field: b13cab7b-f5c5-4387-90a7-64620f7a6e73 # Navi
fieldLayouts:
  79e13098-fb63-43f5-a048-a418660b4491:
    tabs:
      -
        elements:
          -
            fieldUid: 67f8bf4c-3979-4564-9d1c-ed5920a87f24 # Link Text
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: f5aea78d-8ebe-4868-bc02-f4de64aedd2d # Link Destination
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  67f8bf4c-3979-4564-9d1c-ed5920a87f24: # Link Text
    contentColumnType: text
    fieldGroup: null
    handle: linkText
    instructions: ''
    name: 'Link Text'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  f5aea78d-8ebe-4868-bc02-f4de64aedd2d: # Link Destination
    contentColumnType: string
    fieldGroup: null
    handle: linkDestination
    instructions: ''
    name: 'Link Destination'
    searchable: false
    settings:
      allowSelfRelations: false
      limit: '1'
      localizeRelations: false
      selectionLabel: ''
      showSiteMenu: false
      source: null
      sources: '*'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: null
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Entries
handle: navLink
name: 'Nav Link'
sortOrder: 1
