fieldLayouts:
  3297705c-24b9-4a4f-9b44-990fd3c8ccc3:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\EntryTitleField
            warning: null
            width: 100
          -
            fieldUid: c32944d8-cc7d-4860-97dd-e164dfda947e # Hero Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 1bf017fc-87c7-4ae3-b857-1826939ce2be # Hero Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Hero
        sortOrder: 1
      -
        elements:
          -
            fieldUid: d65e3279-43b8-45ed-b494-8f10ee772957 # Featured Story
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: 'Featured Story'
        sortOrder: 2
      -
        elements:
          -
            fieldUid: b4609a50-b4a3-4fc9-9b23-3c87928047fd # Riders Intro Content
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: e574e269-2b5e-4770-8da3-1be40c8e13e0 # Riders
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Riders
        sortOrder: 3
handle: home
hasTitleField: false
name: Home
section: cc5e9c31-6dc8-45d9-a0bb-596309ba5b53 # Home
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
